from . import product_template
from . import product_product
from . import product_supplierinfo
from . import product_supplierinfo_cost_history
from . import product_cost_schedule
from . import product_pricelist
from . import res_config_settings
from . import purchase_order
from . import purchase_order_line
